variables:
  - &buildx-plugin 'docker.io/woodpeckerci/plugin-docker-buildx:5.0.0'
  - &repo 'woodpeckerci/plugin-ready-release-go'
  - &platforms 'linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le'

when:
  - event: [pull_request, tag, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: dryrun
    image: *buildx-plugin
    settings:
      dry_run: true
      repo: *repo
      platforms: *platforms
      tag: test
    when:
      - event: pull_request

  - name: publish-next
    image: *buildx-plugin
    settings:
      repo: *repo
      username: woodpeckerbot
      platforms: *platforms
      tag: next
      password:
        from_secret: docker_password
    when:
      - branch: ${CI_REPO_DEFAULT_BRANCH}
        event: push

  - name: publish-tag
    image: *buildx-plugin
    settings:
      repo: *repo
      username: woodpeckerbot
      platforms: *platforms
      tag: [latest, '${CI_COMMIT_TAG}']
      password:
        from_secret: docker_password
    when:
      - event: tag
