steps:
  install:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm i

  unit-test:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm test

  typecheck:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm typecheck

  format:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm format:check

when:
  - event: pull_request
  - event: push
    branch: main
  - event: tag
