variables:
  - &deno_image 'docker.io/denoland/deno:2.9.3'

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: tag

steps:
  - name: install
    image: *deno_image
    commands:
      - deno install

  - name: unit-test
    image: *deno_image
    commands:
      - deno task test

  - name: typecheck
    image: *deno_image
    commands:
      - deno task check

  - name: format
    image: *deno_image
    commands:
      - deno task format:check
