steps:
  install:
    image: node:18-alpine@sha256:435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d
    commands:
      - corepack enable
      - pnpm i

  unit-test:
    image: node:18-alpine@sha256:435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d
    commands:
      - corepack enable
      - pnpm test

  typecheck:
    image: node:18-alpine@sha256:435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d
    commands:
      - corepack enable
      - pnpm typecheck

when:
  - event: pull_request
  - event: push
    branch: main
  - event: tag
