steps:
  install:
    image: node:20-alpine
    commands:
      - corepack enable
      - pnpm i

  unit-test:
    image: node:20-alpine
    commands:
      - corepack enable
      - pnpm test

  typecheck:
    image: node:20-alpine
    commands:
      - corepack enable
      - pnpm typecheck

when:
  - event: pull_request
  - event: push
    branch: main
  - event: tag
